# ============================================================
# DSA-HGN Bone Stream Configuration - Stabilized Version v2.1
# ============================================================
# ✅ 核心修复：
# 1. 大幅提高熵损失权重 (0.01 -> 0.1) - 让超图真正学习
# 2. 降低辅助任务权重 - 避免压垮分类任务
# 3. 适度降低学习率 - 配合更强的正则化
# 4. 温度退火已在代码中实现 (初始0.8 -> 最终0.1)
# ============================================================

work_dir: ./work_dir/SHREC/bone2_stable_v2.1

# ============================================================
# 基础训练参数
# ============================================================
phase: train
save_result: True
start_epoch: 0
num_epoch: 100                    # 训练100轮
use_gpu: True
device: [0]

# 日志和保存
log_interval: 100
save_interval: 1
eval_interval: 1
save_log: True
print_log: True
pavi_log: False

# ============================================================
# 数据加载器
# ============================================================
train_feeder: feeder.feeder_hgt.Feeder
test_feeder: feeder.feeder_hgt.Feeder
num_worker: 4

train_feeder_args:
  data_path: /Users/gzp/Desktop/exp/DATA/SHREC2017_data/train_data.npy
  label_path: /Users/gzp/Desktop/exp/DATA/SHREC2017_data/train_label.pkl
  split: train
  random_choose: True
  random_shift: True              # 时序增强
  random_rot: True                # 旋转增强
  random_move: False              # 平移增强（关闭以减少复杂度）
  repeat: 5                       # 数据重复5次
  normalization: False
  window_size: 180
  debug: False
  use_mmap: True
  # HGT特征提取器参数
  use_sg: True                    # Savitzky-Golay滤波
  sg_window: 9
  sg_order: 2
  use_angles: True                # 骨骼间夹角特征
  use_rotations: True             # 旋转轴特征

test_feeder_args:
  data_path: /Users/gzp/Desktop/exp/DATA/SHREC2017_data/val_data.npy
  label_path: /Users/gzp/Desktop/exp/DATA/SHREC2017_data/val_label.pkl
  split: test
  debug: False
  use_mmap: True
  normalization: False
  window_size: 180
  use_sg: True
  sg_window: 9
  sg_order: 2
  use_angles: True
  use_rotations: True

batch_size: 32
test_batch_size: 32
debug: False

# ============================================================
# 模型配置
# ============================================================
model: net.dsa_hgn.Model

model_args:
  in_channels: 8                  # HGT特征维度: 3(vec) + 1(len) + 1(angle) + 3(rot)
  base_channels: 64               # 基础通道数
  num_class: 14                   # SHREC 14类手势
  num_person: 1                   # 单手
  graph: graph.shrec_line.Graph   # 线图(骨骼流)
  graph_args:
    labeling_mode: spatial
  num_point: 21                   # 骨骼数量
  num_hyperedges: 12              # 动态超边数量
  k_neighbors: 4                  # KNN邻居数
  adaptive: True                  # 自适应邻接矩阵
  use_virtual_conn: True          # 使用超图虚拟连接
  num_stages: 10                  # TCN-GCN层数
  inflate_stages: [5, 8]          # 通道膨胀阶段
  down_stages: [5, 8]             # 时序下采样阶段
  data_bn_type: VC                # BatchNorm类型
  drop_out: 0.15                  # Dropout率
  temperature: 0.1                # ✅ [关键] 最终温度（初始温度自动设为0.8）

weights: null
ignore_weights: []
loss: null
loss_args: {}

# ============================================================
# ✅ 优化器配置 - 适度降低学习率
# ============================================================
optimizer: SGD
optimizer_args: {}

base_lr: 0.03                     # ✅ 从0.05降低到0.03
step: [40, 60, 80]                # 多阶段衰减
lr_decay_rate: 0.1                # 衰减率
nesterov: True
weight_decay: 0.001               # 权重衰减
warm_up_epoch: 15                 # Warmup轮数

# ============================================================
# ✅ 梯度裁剪
# ============================================================
grad_clip_norm: 1.0               # 梯度裁剪阈值

# ============================================================
# ✅✅✅ 损失权重配置 - 核心修复！！！
# ============================================================
stream: bone                      # 骨骼流

# ============================================================
# ✅ [最关键的修复] 超图正则化损失权重
# ============================================================
lambda_entropy: 0.1               # ✅✅✅ 从0.01提升10倍到0.1！
                                  # 这是最关键的修改 - 让超图真正学习稀疏结构

lambda_ortho: 0.02                # ✅ 从0.05降低到0.02
                                  # 原型正交损失 - 降低权重，给模型更多自由度

lambda_physical: 0.02             # ✅ 从0.05降低到0.02
                                  # 物理约束损失 - 降低权重，避免过度约束

# ============================================================
# 辅助任务损失权重 - 防止压垮主分类任务
# ============================================================
lambda_reg: 0.05                  # ✅ 从0.1降低到0.05
                                  # 回归MSE损失权重

lambda_bone: 0.03                 # ✅ 从0.05降低到0.03
                                  # 骨骼方向一致性损失权重

# ============================================================
# 废弃参数（保留兼容性）
# ============================================================
lambda_sparsity: 0.0              # 已废弃，使用lambda_entropy代替
mining_epoch: 1000000             # 禁用困难样本挖掘
topk: 1

# ============================================================
# 评估配置
# ============================================================
show_topk: [1, 5]

# ============================================================
# 预期效果对比
# ============================================================
# 修复前（原配置）:
#   Epoch 1: 37.74% | loss_ent: 1.85 (停滞)
#   Epoch 2: 40.24% | loss_ent: 1.85 (无变化)
#   Epoch 3: 35.48% ❌ (暴跌)
#   Epoch 4: 24.64% ❌❌ (崩溃)
#
# 修复后（预期）:
#   Epoch 1: 38-42% | loss_ent: 1.75 (开始下降)
#   Epoch 2: 44-48% | loss_ent: 1.65 (持续下降)
#   Epoch 3: 50-54% ✅ (稳定上升)
#   Epoch 4: 55-60% ✅ (持续增长)
#   Epoch 8: 65-70%
#   Epoch 20: 75-82%
#   Epoch 40: 85-90%
#   Epoch 60+: 90-94%
#
# 关键指标监控：
# 1. loss_ent 应该从 ~1.75 降到 ~1.0-1.2（而非停滞在1.85）
# 2. 每10轮应该看到 "Temperature: X.XXXX" 日志
# 3. Top1准确率应该单调上升，无暴跌
# 4. loss_orth 应该在 0.001-0.01 范围（而非0.0000）
# ============================================================